### PR TITLE
Add automatic import sorting

### PR DESCRIPTION
**Pull request by iMoses**

### CODE REVIEW

**Comment by olegat** [comment]
LGTM, but this will almost certainly cause merge conflict with all other open PRs.

Can we hold off on merging this and re-run the formatter at EoD when other PRs have been reviewed & merged? This would make more sense than having everyone resolve conflicts on an individual basis.

**Review by alantreadway — APPROVED** [review]
LGTM, thanks for this!

**Comment by iMoses** [comment]
> LGTM, but this will almost certainly cause merge conflict with all other open PRs.
> 
> Can we hold off on merging this re-run the formatter at EoD when other PRs have been reviewed & merged? This would make more sense than having everyone resolve conflicts on an individual basis.

I don't think it matters much because you can decline the import changes and just run formatting again, but we can also delay the merge if the team prefers. I would advise to merge right after this is pushed anyhow.

Anyhow, there's still one bug which is making sure `mdoc` files are included, I'm looking into it now.

**Comment by olegat** [comment]
> > LGTM, but this will almost certainly cause merge conflict with all other open PRs.
> > Can we hold off on merging this re-run the formatter at EoD when other PRs have been reviewed & merged? This would make more sense than having everyone resolve conflicts on an individual basis.
> 
> I don't think it matters much because you can decline the import changes and just run formatting again, but we can also delay the merge if the team prefers. I would advise to merge right after this is pushed anyhow.
> 
> Anyhow, there's still one bug which is making sure `mdoc` files are included, I'm looking into it now.

I'm not fussed either way (merge this PR now or merge it EoD), but as long as everyone is onboard with the decision then I'm okay.

**Comment by iMoses** [comment]
Closing this PR, @alantreadway would push these changes at EoD.

**Pull request closed without merging**
