### PR TITLE
AG-13162 Bump angular version

### PR DESCRIPTION
**Pull request by jacobp100**
https://ag-grid.atlassian.net/browse/AG-13162

### CODE REVIEW

**Review by StephenCooper — COMMENTED** [review]
Yeah, looks ok to me.

**Review by StephenCooper — APPROVED** [review]

**Comment by StephenCooper** [comment]
Are you examples running v17?

**Comment by alantreadway** [comment]
> Are you examples running v17?

I've confirmed this is the case.

**Review by alantreadway — APPROVED** [review]
LGTM

**Pull request merged**
