### PR TITLE
AG-11757 Remove includeConsumedEvents property

### PR DESCRIPTION
**Pull request by olegat**
https://ag-grid.atlassian.net/browse/AG-11757

This property adds unnecessary complexity to the RegionManager class. So instead just call fireEvent everytime in the listener.

### CODE REVIEW

**Comment by olegat** [comment]
TODO:
- [x] Check this change does not affect the annotations https://charts.ag-grid.com/javascript/annotations/#adding--editing
- [x] Check this change does not break page-scrolling when zoom is disabled.

**Review by jacobp100 — APPROVED** [review]
Just to check - events are propagated through everything even when `preventDefault` is called, and we just ignore events that are `defaultPrevented` in the handler?

**Comment by olegat** [comment]
> Just to check - events are propagated through everything even when `preventDefault` is called, and we just ignore events that are `defaultPrevented` in the handler?

The former "events are propagated through everything even when `preventDefault` is called"

**Review by alantreadway — APPROVED** [review]
LGTM

**Pull request merged**
