### PR TITLE
AG-NONE Add guard for getComputedStyle

### PR DESCRIPTION
**Pull request by olegat**

### CODE REVIEW

**Comment by iMoses** [comment]
I don't think we should add `getComputedStyle` to `verifiedGlobals` because it's part of `window`, making it a bit redundant. 
If there's only one place that may not have it in certain cases (I'm assuming tests or thumbnail creations?) you could use optional chaining. (e.g. `getComputedStyle?.(focusableParent).opacity === '1'`

**Comment by olegat** [comment]
I've changed it to just `getComputedStyle?.(focusParent)`. I cannot remember how to reproduce the original error, so I do not know whether this will work correctly. It seems to work properly when I run it locally.

**Comment by olegat** [comment]
I'm still seeing errors when running `nx dev`

**Comment by olegat** [comment]
` getWindow().getComputedStyle(focusParent)` seems to work as intended.

**Pull request merged**
