### PR TITLE
AG-8564 Calculate Axis layout before rendering

### PR DESCRIPTION
**Pull request by alexanderby**

### CODE REVIEW

**Review by alantreadway — COMMENTED** [review]
I would have expected some code to have been removed? Is the layout logic replicated in the application phase?

**Comment by alexanderby** [comment]
Some calculation results can be reused. I will try finding the cause for a little axis shift and refactor a bit.

**Review by alantreadway — APPROVED** [review]
LGTM

**Comment by alexanderby** [comment]
I can't believe it!

**Pull request merged**
