### PR TITLE
AG-12519 - Reduce duplication of text measuring and wrapping

### PR DESCRIPTION
**Pull request by manapeirov**
PR for https://ag-grid.atlassian.net/browse/AG-12519

### CODE REVIEW

**Review by alantreadway — COMMENTED** [review]
LGTM

**Review by lsjroberts — APPROVED** [review]
LGTM. May just need a rebase to fix the broken snapshots, if it's not caused by this (which seems unlikely).

**Review by alantreadway — APPROVED** [review]

**Pull request merged**
