### PR TITLE
AG-9186 Replace old yAxis with new axes.y

### PR DESCRIPTION
**Pull request by olegat**

### CODE REVIEW

**Review by alantreadway — COMMENTED** [review]
Fix looks good in terms of practical approach - but I'm wondering if the root-cause of why this problem wasn't spotted is because `HighlightNodeDatum.series` is of type `any`? 
https://github.com/ag-grid/ag-charts/blob/latest/packages/ag-charts-community/src/chart/interaction/highlightManager.ts#L9

Could you see if tightening the definition there is possible, and if there are any other cases that need to be updated?

e.g. I'm thinking along the lines of:
```
   series: { axes: { y: { id: string } } } 
```

(the actual `Series` type is too broad, and I want to try and decrease coupling between implementation classes)

**Comment by olegat** [comment]
Yes, changing the `HighlightNodeDatum.series` type from `any` to `{ axes: { y: { id: string } } }` catches this error if I revert the fix. I'll see whether the same thing can be done to `HighlightNodeDatum.itemId` and `HighlightNodeDatum.datum`.

**Comment by olegat** [comment]
It appears that the `HighlightNodeDatum.series` type is set to `any` due to a mixup between [`abstract class Series`](https://github.com/ag-grid/ag-charts/blob/1c9d5ad63be0e7f2e31914bbdd73ac032fea8dcf/packages/ag-charts-community/src/chart/series/series.ts#L308) and the [`interface Series`](https://github.com/ag-grid/ag-charts/blob/1c9d5ad63be0e7f2e31914bbdd73ac032fea8dcf/packages/ag-charts-community/src/chart/dataService.ts#L1). According to the compiler, legend.ts is using the `interface Series` type [here](https://github.com/ag-grid/ag-charts/blob/1c9d5ad63be0e7f2e31914bbdd73ac032fea8dcf/packages/ag-charts-community/src/chart/legend.ts#L738) and [here](https://github.com/ag-grid/ag-charts/blob/1c9d5ad63be0e7f2e31914bbdd73ac032fea8dcf/packages/ag-charts-community/src/chart/legend.ts#L858) when passing the `series` variable to the [`HighlightManager.updateHighlight`](https://github.com/ag-grid/ag-charts/blob/1c9d5ad63be0e7f2e31914bbdd73ac032fea8dcf/packages/ag-charts-community/src/chart/interaction/highlightManager.ts#L46) function.

So tightening the definition of `HighlightNodeDatum.series` would involve updating the definition of `interface Series` to include an `axes` member. It's unclear to me whether that it desirable. The Y axis would also need be to included in `axes`, because it's used here: [crosshair.ts:221](https://github.com/ag-grid/ag-charts/blob/1c9d5ad63be0e7f2e31914bbdd73ac032fea8dcf/packages/ag-charts-enterprise/src/crosshair/crosshair.ts#L221).

Here's what I've got so far:
```diff
diff --git a/packages/ag-charts-community/src/chart/dataService.ts b/packages/ag-charts-community/src/chart/dataService.ts
index 14467cf7..53a3426d 100644
--- a/packages/ag-charts-community/src/chart/dataService.ts
+++ b/packages/ag-charts-community/src/chart/dataService.ts
@@ -1,6 +1,7 @@
 interface Series {
     id: string;
     type: string;
+    axes: { y: { id: string }; x: { id: string } };
     getLegendData(): any[];
 }
 
diff --git a/packages/ag-charts-community/src/chart/interaction/highlightManager.ts b/packages/ag-charts-community/src/chart/interaction/highlightManager.ts
index 8991fe5f..6a5289f4 100644
--- a/packages/ag-charts-community/src/chart/interaction/highlightManager.ts
+++ b/packages/ag-charts-community/src/chart/interaction/highlightManager.ts
@@ -6,7 +6,7 @@ interface HighlightState {
 }
 
 interface HighlightNodeDatum {
-    readonly series: any;
+    readonly series: { axes: { y: { id: string }; x: { id: string } } };
     readonly itemId?: any;
     readonly datum: any;
     readonly xKey?: string;
diff --git a/packages/ag-charts-enterprise/src/crosshair/crosshair.ts b/packages/ag-charts-enterprise/src/crosshair/crosshair.ts
index 70f08da1..3f09d090 100644
--- a/packages/ag-charts-enterprise/src/crosshair/crosshair.ts
+++ b/packages/ag-charts-enterprise/src/crosshair/crosshair.ts
@@ -6,7 +6,7 @@ import { CrosshairLabel } from './crosshairLabel';
 type AgCrosshairLabelRendererResult = any;
 
 const { Group, Line, BBox } = _Scene;
-const { Validate, NUMBER, BOOLEAN, OPT_COLOR_STRING, OPT_LINE_DASH, Layers, ChartAxisDirection } = _ModuleSupport;
+const { Validate, NUMBER, BOOLEAN, OPT_COLOR_STRING, OPT_LINE_DASH, Layers } = _ModuleSupport;
 
 export class Crosshair extends _ModuleSupport.BaseModuleInstance implements _ModuleSupport.ModuleInstance {
     @Validate(BOOLEAN)
@@ -217,8 +217,8 @@ export class Crosshair extends _ModuleSupport.BaseModuleInstance implements _Mod
         const hasCrosshair =
             currentHighlight &&
             currentHighlight.datum &&
-            (currentHighlight.series.axes[ChartAxisDirection.X]?.id === axisCtx.axisId ||
-                currentHighlight.series.axes[ChartAxisDirection.Y]?.id === axisCtx.axisId);
+            (currentHighlight.series.axes.x.id === axisCtx.axisId ||
+                currentHighlight.series.axes.y.id === axisCtx.axisId);
 
         if (!hasCrosshair) {
             this.activeHighlight = undefined;
```

Please let me know your thoughts.

**Comment by olegat** [comment]
Discussed offline. I've uploaded a commit with the changes in the previous comment.

**Comment by olegat** [comment]
There are more errors that I didn't notice due to the rollup plugin cache bug. I've created a new bug AG-9271 to cleanup the `HighlightNodeDatum` type and updated this PR to just address the runtime errors.

**Review by alantreadway — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
